### ISSUE TITLE
The game stops suddenly

### ISSUE THREAD

**Issue by kshitijb** [frnsys/the_founder#126]
Hi, The game has been stopping after 2-3 seconds. I have to pause and refresh the page to let it load again for 2-3 seconds. I am seeing an error message in the developer console. I am using chrome latest version.

![screen shot 2017-01-28 at 1 15 01 am](https://cloud.githubusercontent.com/assets/4145434/22385253/f45caa76-e4f7-11e6-83d1-ac7fda28b928.png)

**Comment by Meegul** [comment]
I'm also having this issue, running Chrome 55 (64-bit) on Linux.

**Comment by nstr10** [comment]
I'm also having this issue, running Chrome 55 (64-bit) on Windows 7.

**Comment by frnsys** [comment]
I pushed a fix that should resolve this (5ea4d07071c8c9941e7ae7ecb353ff431eaaf6b6)

closing for now, feel free to re-open if the issue remains

**Comment by barneyjackson** [comment]
For anyone interested in fixing a save game that experienced this bug:

1. Go to the [http://thefounder.biz/play/](http://thefounder.biz/play/) main menu/splash page.
1. In your browser JS console `localStorage.saveGame` and copy the output.
2. Search for an instance of `{}` (empty object), should be located in a `"conditions": [...]` array if it's this bug.
3. Remove the `{}`.
3. Ensure your editor hasn't converted any `"`s to `“` or anything silly.
4. Copy the entire save game back to your clipboard.
4. Back in the JS console `localStorage.saveGame = JSON.stringify(<paste edited save game>);`
5. Now click "Load Game".
6. Voilà
