### ISSUE TITLE
Verticals never unlock?

### ISSUE THREAD

**Issue by addisonj** [frnsys/the_founder#128]
The first game I played, verticals unlocked pretty quickly.

In another game, it wasn't until I was a few locations unlocked and lobbying done that I realized I didn't have the verticals menu.

This looks to be controlled via the onboarding, however I couldn't figure out why the menu isn't rendering

**Comment by frnsys** [comment]
someone reported a similar problem where the Product Types menu wouldn't show up. I think the way I'm checking if if a menu item should be unlocked sometimes gets skipped over if there are multiple conditions being met. I'll push up a change that should be more flexible in this regard.
