### ISSUE TITLE
My little blue product guy keeps disapearing

### ISSUE THREAD

**Issue by rtconner** [frnsys/the_founder#130]
On "The Market" screen, this has happened three times that my blue ball just disappears from the map.

<img width="856" alt="screen shot 2017-01-28 at 7 55 47 am" src="https://cloud.githubusercontent.com/assets/334533/22396779/e1b1978c-e52f-11e6-88b1-842a5d9f75e7.png">

It always happens when I click and drag. After the click, but before the drag. Like right as I start to drag the blue ball just disappears. Only happening when I have two or more movement points, not happening when I have one movement point.

On a Mac with Firefox if that helps. Use the touchpad for mouse.

**Comment by rtconner** [comment]
This also happened to me on Safari.

**Comment by imsky** [comment]
happened in chrome too

**Comment by frnsys** [comment]
a few others have reported this as well, I'll take a look

**Comment by frnsys** [comment]
ok just managed to reproduce this on my end. hopefully i'll have a fix soon!
