### ISSUE TITLE
Research task doesn't become visible

### ISSUE THREAD

**Issue by rbhalla** [frnsys/the_founder#134]
Seems like the menu item isn't rendered at all. I tried skipping onboarding in settings but that didn't work. Renaming one of the menu item classes to `start-research` allowed me to start them

**Comment by frnsys** [comment]
is this a game you've been playing for awhile? this sounds similar to a bug others have encountered that I pushed a fix for recently. You may have to start a new game for the fix to work.

**Comment by rbhalla** [comment]
I started a few hours ago before submitting this bug (it's an addictive game). Do you mind pointing to the commit just to see if I started a game before/after?

**Comment by frnsys** [comment]
sure thing, it's commit: 0eedf8277712a70213f0ee1de79a7fb6a692445e

**Comment by rbhalla** [comment]
Ahh ok, that may be it. It's a shame because I was doing so well in my current game...thanks for the quick response though!

**Comment by frnsys** [comment]
sorry :( let me know if it's still an issue!
