### ISSUE TITLE
"Discovered Products" will show a question mark panel for an impossible product ("name"":Default")

### ISSUE THREAD

**Issue by mikemunger** [frnsys/the_founder#139]
On the "Discovered Products" menu, there are 68 items - 67 of these are product recipes but one cannot be discovered, because as the source code reveals, it is the "name":"Default" failed product.

So completionists might think they are missing a product discovery.

Super fun game! Thanks for making it.

**Comment by frnsys** [comment]
thanks for pointing this out!
