### ISSUE TITLE
patent trolls

### ISSUE THREAD

**Issue by hemna** [frnsys/the_founder#142]
The patent trolls happens way to frequently.   I've been playing 10 minutes and in the last 2 year cycles I'm down $-100 million in cash.  makes it impossible to play.  I think the patent troll happened 5 or 6 times in a 2 year cycle.

**Comment by roneifeix** [comment]
olá, infelizmente o mesmo está ocorrendo comigo. o jogo perde a graça deste modo :( 
poderia alterar este detalhe, ou então, em qual arquivo posso fazer esta edição?

**Comment by frnsys** [comment]
I doubled the amount of time between patent troll events. Let me know if it's still too frequent.
