### ISSUE TITLE
Research not unlocking

### ISSUE THREAD

**Issue by nkatz565** [frnsys/the_founder#145]
Not completely sure what causes it, but I've seen multiple people, including myself, who research never got unlocked for. 

If I had to take a guess, it's due to the file /data/onboarding.json

Under the research conditions, it has the following 

```
"type": "productsLaunched",
      "op": "eq",
      "val": 5

```

I believe what is happening is that the user is developing 2 products at once while their count is at 4. When the two products launch one after another, the product count is set to 6 before the onboarding event is triggered. If the eq was changed to a gt, it should be an easy fix.

Edit: strangely enough, after this glitch occurs, you can't even unlock research by skipping the onboarding. Not sure why that is.

**Comment by frnsys** [comment]
thanks for pointing this out. this was a bug with a bunch of other unlocks which required me making a small change...forgot to make it for research.
