### ISSUE TITLE
The auto complete button should toggle colour

### ISSUE THREAD

**Issue by Cephlin** [frnsys/the_founder#149]
In the latest PR, the ability to auto complete a project was added. There is a bug with this in that the button doesn't toggle colour meaning you have no way of knowing whether it will or will not auto complete.

@frnsys @notVitaliy

**Comment by seantitus** [comment]
To add on to this, the "Repeat this task" button doesn't stay green if you reopen the task, and it probably should.

**Comment by notVitaliy** [comment]
@cephlin yea, I noticed that on the live site. It works when testing locally. I didn't have a chance to look into it yet, maybe it's a cdn caching issue?

@seantitus also noticed this bug. I know exactly how to fix it, just need some free time to do so.
