### ISSUE TITLE
Research screen missing

### ISSUE THREAD

**Issue by Orgmir** [frnsys/the_founder#151]
Hey, cool game you guys have here!

I've been playing for a while, and I've figure that I should be able to research stuff. But after googling for a bit I can't seem to find where to research. I must be missing a button or a screen.

Here is a screenshot of my current game, is there any button missing? Or I'm totally missing the spot??
![the_founder](https://cloud.githubusercontent.com/assets/1656395/22618678/071d02e2-eb37-11e6-9d00-7af16e4ebaa7.PNG)

**Comment by frnsys** [comment]
this may be the same issue as #145...you might need to start a new game for it to work properly.

but you should also be able to go into the settings and select "skip onboarding" to show it

**Comment by Orgmir** [comment]
AH I see, that must be it then! I'll try a new game ^^ I'll close the issue.
