### ISSUE TITLE
"buy" button for some perks still clickable when funds are insufficient

### ISSUE THREAD

**Issue by devinhalladay** [frnsys/the_founder#73]
I'm going through onboarding rn and found a bug where after I purchased the office keg I'm trying to buy a ping pong table and am $500 short, but the "Buy" button is still clickable. http://pasteboard.co/fShPn0yGc.png (screenshot)

**Comment by frnsys** [comment]
thanks for pointing this out, i'll take a look - do you remember if there were onboarding messages right before this happened?

**Comment by frnsys** [comment]
nvm, just ran into it myself under different circumstances
