### ISSUE TITLE
Firefox loading issue

### ISSUE THREAD

**Issue by frnsys** [frnsys/the_founder#88]
> It appears to be completely unusable on firefox 45.4.0 on Debian. After clicking "new game", all I see is the background gradient.

**Comment by frnsys** [comment]
seems ok with Firefox 49.0 on Ubuntu 14.04. perhaps there's something incompatible about older versions...need to look more into this.

**Comment by frnsys** [comment]
(need to do more extensive testing on firefox anyways)

**Comment by Powersource** [comment]
Same for me on Chrome, but it works in Firefox (linux). This is always the case for me with opengl. Just fyi. I don't expect this to change due to my old gpu.

**Comment by frnsys** [comment]
ok it sounds like there isn't much I can do about this one then :\
