### ISSUE TITLE
space still not being unlocked properly?

### ISSUE THREAD

**Issue by frnsys** [frnsys/the_founder#98]
> , unable to unlock Space or the alcubierre drive because the game seemed to think I didn't have the hardware vertical, though i did.

**Comment by frnsys** [comment]
haven't been able to reproduce this, but will keep an eye on it  👀

**Comment by addisonj** [comment]
Just ran into this as well, not sure if it was the hardware vertical or some other condition.

I had performed all other research but was never given this option. This in the same game where I wasn't show verticals which I eventually hacked around by changing the game state

**Comment by frnsys** [comment]
hm it may have been fixed by 8c014566b96bed4319f554bf027a41935be01aa5 then
